### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MarvelDarrenW** [SadesXD/GTPS-Auto-Backup-Discord-Bot#3]
internal/modules/cjs/loader.js:1131
    throw err;
    ^

SyntaxError: C:\Users\Onigirivps2\Desktop\GTPS-Auto-Backup-Discord-Bot-main\config.json: Unexpected token U in JSON at position 235
    at parse (<anonymous>)
[90m    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1128:22)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:974:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:92:18)[39m
    at Object.<anonymous> (C:\Users\Onigirivps2\Desktop\GTPS-Auto-Backup-Discord-Bot-main\index.js:13:27)
[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:950:32)[39m
Press any key to continue . . .

welp

**Comment by SadesXD** [comment]
fixed
